/* Configurable report navigation, live refresh, and explicit exports. */
(function(){
  'use strict';
  const C=window.TPO_CONFIG,D=window.TPO_DATA,V=window.TPO_VIEWS,S=window.TPOCore.settings,U=window.TPO_SETTINGS_UI;
  const state={data:null,error:null,settings:S.normalize({}),fullAnalysis:null,snapshot:null,notice:'',busy:false};let liveData=null,refreshId=0;
  const visible=()=>S.visible(state.settings,state.data?._analysis),customers=()=>S.customerList(state.settings,state.data?._analysis);
  function home(){const sections=visible();return sections.some(s=>s.id===state.settings.home)?state.settings.home:sections[0]?.id||'setup';}
  function nav(){const el=document.getElementById('primary-nav');el.replaceChildren();[...visible(),{id:'setup',label:'Setup & data health'}].forEach(s=>{const a=document.createElement('a');a.href='#/'+s.id;a.textContent=s.label||s.id;el.append(a);});document.getElementById('as-of').textContent=state.data?'As of '+(state.data._analysis.latest?.month||'unavailable')+(state.snapshot?' · Archived snapshot':''):'';document.body.classList.toggle('compact-report',state.settings.density==='compact');active();}
  function active(){const cur=(location.hash||'#/').slice(1);document.querySelectorAll('#primary-nav a').forEach(a=>{const yes=cur===a.hash.slice(1)||(a.hash==='#/customers'&&cur.startsWith('/customers/'));a.classList.toggle('active',yes);if(yes)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});}
  function route(){const parts=(location.hash||'#/').replace(/^#\/?/,'').split('/').filter(Boolean);return {name:parts[0]||home(),slug:parts[1]};}
  function mount(node){V.disposeAllCharts();const view=document.getElementById('view');view.replaceChildren(node);if(state.notice){const n=document.createElement('p');n.className='data-health-banner';n.textContent=state.notice;view.prepend(n);}if(state.snapshot){const n=document.createElement('p');n.className='data-health-banner';n.textContent='Archived snapshot captured '+state.snapshot.capturedAt+'. Live data is not being refreshed.';view.prepend(n);}if(state.data?._issues.some(i=>i.level!=='info')&&route().name!=='setup'){const a=document.createElement('a');a.className='data-health-banner';a.href='#/setup';a.textContent='Some source data needs attention. Review Setup & data health.';view.prepend(a);}}
  function page(id,slug){if(id!=='customers')return V[id](state);const root=V.customer(state,slug||customers()[0]?.slug),sub=document.createElement('nav');sub.id='sub-nav';sub.setAttribute('aria-label','Customer pages');customers().forEach(c=>{const a=document.createElement('a');a.href='#/customers/'+c.slug;a.textContent=c.label||c.name;if(c.slug===slug)a.className='active';sub.append(a);});root.prepend(sub);return root;}
  function render(){const r=route();if(r.name==='setup'||state.error){mount(V.setup(state));active();return;}if(!state.data){mount(V.loading());return;}const section=visible().find(s=>s.id===r.name),list=customers();if(!section||(r.name==='customers'&&r.slug&&!list.some(c=>c.slug===r.slug))){state.notice='That section is hidden or unavailable in this report configuration.';history.replaceState(null,'','#/'+home());mount(home()==='setup'?V.setup(state):page(home()));active();return;}if(r.name==='customers'&&!r.slug){r.slug=list[0]?.slug;history.replaceState(null,'','#/customers/'+r.slug);}if(!state.data.monthly.length&&r.name!=='about'){mount(V.setup(state));return;}mount(page(r.name,r.slug));active();}
  function applyData(data,settings){state.settings=S.normalize(settings);state.data=D.shape(data._rawMap,data._errorDetails||[],state.settings);state.data._loadedAt=data._loadedAt;state.fullAnalysis=window.TPOCore.analyze(Object.entries(data._rawMap).map(([name,raw])=>({name,raw})));window.TPO_COMPUTE.setFormat?.(state.settings,state.data.assumptions.params.Currency||C.CURRENCY||'THB');window.TPO_CHART_SETTINGS=state.settings;const company=state.data.content['company.name']||C.COMPANY||'TPO Wellness',title=state.data.content['report.title']||C.REPORT_TITLE||'Monthly Performance';document.getElementById('header-brand').textContent=company;document.getElementById('header-title').textContent=title;document.title=company+' — '+title;document.getElementById('footer-note').textContent='Reported in '+(state.data.assumptions.params.Currency||C.CURRENCY||'THB');nav();render();}
  async function refresh(){if(state.snapshot)return;const id=++refreshId;state.busy=true;state.notice='';try{const data=await D.load();if(id!==refreshId)return;liveData=data;state.error=null;applyData(data,U.effective(data._sharedSettings));}catch(e){if(id!==refreshId)return;state.error=e;state.notice=state.data?'Refresh failed. Previously loaded data is retained.':'';render();}finally{state.busy=false;}}
  function exportPages(){return visible().filter(s=>s.export).flatMap(s=>s.id==='customers'?customers().filter(c=>c.export).map(c=>({id:s.id,slug:c.slug,label:c.label||c.name})):[{id:s.id,label:s.label}]);}
  function printReport(){if(!state.data)return;const pages=exportPages();if(!pages.length){state.notice='No visible sections are selected for export.';render();return;}const root=document.createElement('article');root.id='print-report';const heading=document.createElement('h1');heading.textContent=(C.COMPANY||'TPO')+' — '+(state.data._analysis.latest?.month||'Report');root.append(heading);pages.forEach(p=>{const src=p.id==='customers'?V.customer(state,p.slug):V[p.id](state),section=document.createElement('section'),h=document.createElement('h2');h.textContent=p.label;section.append(h);src.querySelectorAll('.kpi,.board-table,.briefing,.note-warn').forEach(n=>section.append(n.cloneNode(true)));root.append(section);});document.getElementById('print-report')?.remove();document.body.append(root);window.print();setTimeout(()=>root.remove(),1000);}
  function exportCSV(){if(!state.data)return;const rows=[['Section','Field / period','Values']],a=state.data._analysis;exportPages().forEach(p=>{
    if(p.id==='customers'){a.cq.filter(r=>S.slug(r.customer)===p.slug).forEach(r=>rows.push([p.label,r.period.label,r.values[0]]));a.cm.filter(r=>S.slug(r.customer)===p.slug).forEach(r=>rows.push([p.label,r.period.display,r.values[0]]));}
    else if(['overview','financials','seasonality'].includes(p.id)){rows.push([p.label,'Month',...window.TPOCore.metrics]);a.monthly.forEach(r=>rows.push([p.label,r.month,...window.TPOCore.metrics.map(k=>r[k])]));}
    else if(p.id==='dashboard'){rows.push([p.label,'Metric',...a.dashboard.periods]);a.dashboard.metrics.forEach(m=>rows.push([p.label,m.label,...m.values]));}
    else if(p.id==='working-capital'){rows.push([p.label,'Month','Cash','AR','Inventory','AP','NWC']);a.wc.forEach(r=>rows.push([p.label,r.month,r.cash,r.ar,r.inventory,r.ap,r.nwc]));}
    else if(p.id==='forward-looking'){rows.push([p.label,'Period',...window.TPOCore.metrics,'Risk','Coverage']);a.forward.forEach(r=>rows.push([p.label,r.label,...window.TPOCore.metrics.map(k=>r[k]),r.riskStatus,r.coverage]));}
    else if(p.id==='about')state.data.glossary.forEach(r=>rows.push([p.label,r.term,r.definition]));
  });const escape=v=>{let s=String(v??'');if(typeof v!=='number'&&/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};U.download('tpo-report-'+(a.latest?.period.label||'data')+'.csv','\ufeff'+rows.map(r=>r.map(escape).join(',')).join('\r\n'),'text/csv;charset=utf-8');}
  function saveSnapshot(){if(state.data)U.download('tpo-snapshot-'+(state.data._analysis.latest?.period.label||'report')+'.json',JSON.stringify({schema:'tpo-report-snapshot-v1',engine:'tpo-v5',fingerprint:state.data._fingerprint,capturedAt:state.snapshot?.capturedAt||new Date().toISOString(),settings:state.settings,sources:state.data._rawMap},null,2));}
  function openSnapshot(value){if(!value||value.schema!=='tpo-report-snapshot-v1'||!Number.isFinite(Date.parse(value.capturedAt))||!value.sources||typeof value.sources!=='object'||Array.isArray(value.sources))throw new Error('Invalid report snapshot.');let cells=0;Object.entries(value.sources).forEach(([key,rows])=>{if(['__proto__','constructor','prototype'].includes(key)||!Array.isArray(rows))throw new Error('Invalid snapshot source.');rows.forEach(r=>{if(!Array.isArray(r)||r.some(v=>v!==null&&!['string','number','boolean'].includes(typeof v)))throw new Error('Invalid snapshot cells.');cells+=r.length;});});if(cells>200000)throw new Error('Snapshot exceeds 200,000 cells.');const settings=S.normalize(value.settings),data=D.shape(value.sources,[],settings);if(value.engine!=='tpo-v5'||value.fingerprint!==data._fingerprint)throw new Error('Snapshot validation failed: the data or calculation version differs from the captured report.');state.snapshot=value;state.error=null;refreshId++;applyData(data,settings);}
  window.TPO_APP={refresh,printReport,exportCSV,saveSnapshot,openSnapshot,applySnapshotSettings:s=>{if(state.snapshot)applyData(state.data,s);},returnLive:()=>{state.snapshot=null;if(liveData)applyData(liveData,U.effective(liveData._sharedSettings));else refresh();}};
  window.addEventListener('tpo-settings-change',()=>{state.notice='';if(state.snapshot)applyData(state.data,state.snapshot.settings);else if(liveData)applyData(liveData,U.effective(liveData._sharedSettings));else{state.settings=U.effective(S.normalize({}));nav();render();}});window.addEventListener('hashchange',()=>{state.notice='';render();});
  let resizeTimer;const resize=()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>document.querySelectorAll('[_echarts_instance_]').forEach(n=>window.echarts?.getInstanceByDom(n)?.resize()),120);};window.addEventListener('resize',resize);window.visualViewport?.addEventListener('resize',resize);
  const toggle=document.getElementById('nav-toggle'),navigation=document.getElementById('primary-nav');const close=()=>{navigation.classList.remove('open');toggle.setAttribute('aria-expanded','false');};toggle.addEventListener('click',()=>{const open=navigation.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));});navigation.addEventListener('click',e=>{if(e.target.closest('a'))close();});document.addEventListener('keydown',e=>{if(e.key==='Escape'){close();toggle.focus();}});
  nav();render();refresh();
})();
