/* Setup controls. Only preferences are persisted; financial snapshots are explicit files. */
(function(){
  'use strict';
  const S=window.TPOCore.settings,scope='tpo:settings:v1:'+window.TPO_CONFIG.SHEET_ID;
  let storageError='';
  function read(key,fallback){try{return JSON.parse(localStorage.getItem(scope+key))??fallback;}catch(e){storageError='Browser storage unavailable or invalid; settings remain available for this session.';return fallback;}}
  function write(key,value){try{localStorage.setItem(scope+key,JSON.stringify(value));return true;}catch(e){storageError='Browser storage is unavailable. Download settings to keep your changes.';return false;}}
  let personal=read('',null),sessionSettings=null;
  function effective(shared){try{return S.normalize(sessionSettings||personal||shared);}catch(e){storageError=e.message;return S.normalize(shared);}}
  function apply(value){sessionSettings=S.normalize(value);personal=sessionSettings;write('',personal);window.dispatchEvent(new Event('tpo-settings-change'));}
  function reset(){sessionSettings=null;personal=null;write('',null);window.dispatchEvent(new Event('tpo-settings-change'));}
  function download(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function node(tag,text,attrs={}){const el=document.createElement(tag);if(text!=null)el.textContent=text;Object.entries(attrs).forEach(([k,v])=>el.setAttribute(k,v));return el;}
  function button(label,fn){const b=node('button',label,{type:'button'});b.addEventListener('click',fn);return b;}
  function select(label,values,current){const wrap=node('label',label),input=node('select',null,{'aria-label':label});values.forEach(v=>{const [value,text]=Array.isArray(v)?v:[v,v];const o=node('option',text,{value});input.append(o);});input.value=String(current);wrap.append(input);return {wrap,input};}
  function panel(state){
    const root=node('div',null,{class:'report-settings'}),form=node('form'),status=node('p','',{role:'status'}),settings=state.settings||S.normalize({});
    root.append(node('h2','Report controls'),node('p',state.snapshot?'Viewing an imported snapshot. Changes here affect this view only.':personal?'Personal settings are active in this browser. Reset to follow the shared report defaults.':'Following shared report defaults. Applying changes creates a personal configuration in this browser.'));
    const controls=node('div',null,{class:'settings-fields'}),inputs={};
    const months=(state.fullAnalysis?.monthly||state.data?.monthly||[]).map(r=>[r.period.label,r.month]).reverse();
    const definitions=[['cutoff','Reporting cut-off',[['latest','Latest actual month'],...months]],['home','Opening tab',S.sections.map(s=>[s.id,s.label])],['monthlyRange','Default monthly chart range',[['all','All'],['6m','6 months'],['12m','12 months'],['ytd','Year to date']]],['quarterlyRange','Default quarterly chart range',[['all','All'],['4q','Last 4 quarters'],['8q','Last 8 quarters']]],['money','Amount display',[['auto','Automatic'],['full','Full amounts'],['thousands','Thousands'],['millions','Millions']]],['decimals','Decimal places',['0','1','2']],['density','Table spacing',['comfortable','compact']]];
    definitions.forEach(([key,label,options])=>{const f=select(label,options,settings[key]);if(f.input.value==='')f.input.append(node('option',String(settings[key]),{value:settings[key],selected:''}));inputs[key]=f.input;controls.append(f.wrap);});form.append(controls);
    const tabInputs={},customerInputs={};
    function settingTable(title,items,dest){const section=node('section'),table=node('table',null,{class:'settings-table'}),head=node('tr');['Section','Display','Label','Order','AI input','Export'].forEach(t=>head.append(node('th',t)));table.append(head);
      items.forEach(item=>{const row=node('tr'),r=item.setting;row.append(node('th',item.name,{scope:'row'}));const mode=select(item.name+' display',['show','hide','auto'],r.mode).input;
        const label=node('input',null,{value:r.label,'aria-label':item.name+' label',maxlength:'70'}),order=node('input',null,{type:'number',value:r.order,'aria-label':item.name+' order',min:'0',max:'999'});
        const commentary=node('input',null,{type:'checkbox','aria-label':item.name+' AI input'}),exportBox=node('input',null,{type:'checkbox','aria-label':item.name+' export'});commentary.checked=r.commentary;exportBox.checked=r.export;if(item.noAI){commentary.disabled=true;commentary.checked=false;}
        [mode,label,order,commentary,exportBox].forEach(el=>{const td=node('td');td.append(el);row.append(td);});table.append(row);dest[item.id]={mode,label,order,commentary,exportBox};
      });section.append(node('h3',title),table);form.append(section);}
    settingTable('Report tabs',S.sections.map(s=>({id:s.id,name:s.label,setting:settings.tabs[s.id],noAI:!s.view})),tabInputs);
    settingTable('Customer pages',(state.fullAnalysis?.customers||[]).map((c,i)=>({id:S.slug(c.name),name:c.name,setting:S.rowSetting(settings,S.slug(c.name),c.name,i)})),customerInputs);
    form.append(node('p','Show always displays a section. Auto displays it when usable data exists, including actual zeroes. Visibility never removes revenue from totals. AI and export selections are independent. Hidden sections are omitted from report exports.'));
    function collect(){const value={...settings,tabs:{},customers:{...settings.customers}};Object.entries(inputs).forEach(([k,v])=>value[k]=k==='decimals'?Number(v.value):v.value);for(const [target,fields] of [['tabs',tabInputs],['customers',customerInputs]])Object.entries(fields).forEach(([id,f])=>value[target][id]={mode:f.mode.value,label:f.label.value,order:Number(f.order.value),commentary:f.commentary.checked,export:f.exportBox.checked});return S.normalize(value);}
    const attempt=fn=>()=>{try{fn();}catch(e){status.textContent=e.message;}};
    const actions=node('div',null,{class:'settings-actions'});actions.append(button('Apply in this browser',attempt(()=>{const value=collect();if(state.snapshot)window.TPO_APP.applySnapshotSettings(value);else apply(value);})),button('Reset to shared defaults',()=>reset()),button('Download settings',attempt(()=>download('tpo-report-settings.json',JSON.stringify(collect(),null,2)))),button('Prepare shared settings',attempt(()=>{const text=JSON.stringify(collect(),null,2);sharedText.value=text;sharedText.hidden=false;sharedText.focus();sharedText.select();status.textContent='Copy this configuration, then open Google Sheets → TPO → Report settings and paste it there. Only an authorized spreadsheet editor can save shared defaults.';})));
    const sharedText=node('textarea',null,{'aria-label':'Shared settings JSON',rows:'8',hidden:''});form.append(actions,sharedText);
    const presetName=node('input',null,{placeholder:'Preset name','aria-label':'Preset name',maxlength:'60'}),storedPresets=read(':presets',[]),presets=(Array.isArray(storedPresets)?storedPresets:[]).filter(p=>{try{return typeof p.name==='string'&&!!S.normalize(p.settings);}catch(e){return false;}});
    const preset=select('Saved preset',[['','Choose a preset'],['@board','Board meeting'],['@full','Full management report'],...presets.map((p,i)=>[String(i),p.name])],'');
    const presetBar=node('div',null,{class:'settings-actions'});presetBar.append(preset.wrap,presetName,button('Save preset',attempt(()=>{const name=presetName.value.trim();if(!name)throw new Error('Enter a preset name.');const next=presets.filter(p=>p.name!==name);next.push({name,settings:collect()});if(next.length>30)throw new Error('A maximum of 30 presets is supported.');if(!write(':presets',next))throw new Error(storageError);status.textContent='Preset saved. Reopen Setup to select it.';})),button('Apply preset',attempt(()=>{let value;if(preset.input.value==='@board'){value=S.normalize(settings);['seasonality','about'].forEach(id=>value.tabs[id].mode='hide');value.monthlyRange='12m';value.money='millions';value.decimals=2;}else if(preset.input.value==='@full'){value=S.normalize(settings);Object.values(value.tabs).forEach(r=>r.mode='show');Object.values(value.customers).forEach(r=>r.mode='show');}else value=presets[Number(preset.input.value)]?.settings;if(!preset.input.value||!value)throw new Error('Choose a preset.');if(state.snapshot)window.TPO_APP.applySnapshotSettings(value);else apply(value);})));form.append(node('h3','Presets'),presetBar);
    const upload=node('input',null,{type:'file',accept:'.json,application/json','aria-label':'Import settings or report snapshot'});upload.addEventListener('change',async()=>{try{const file=upload.files[0];if(!file)return;if(file.size>10000000)throw new Error('File exceeds the 10 MB limit.');const parsed=JSON.parse(await file.text());if(parsed.schema==='tpo-report-snapshot-v1')window.TPO_APP.openSnapshot(parsed);else{const value=S.normalize(parsed);if(state.snapshot)window.TPO_APP.applySnapshotSettings(value);else apply(value);}}catch(e){status.textContent=e.message;}});
    form.append(node('h3','Export and archive'),node('p','Snapshots include all loaded source data, including hidden customers, plus commentary, settings and capture time. Import checks the calculation version and data fingerprint. Historical cut-offs recalculate today’s data; they do not recreate earlier source revisions. Print exports contain tables, key figures and briefings.'),upload);
    const exports=node('div',null,{class:'settings-actions'});exports.append(button('Print selected report',()=>window.TPO_APP.printReport()),button('Download selected report data (CSV)',()=>window.TPO_APP.exportCSV()),button('Save report snapshot',()=>window.TPO_APP.saveSnapshot()));if(state.snapshot)exports.append(button('Return to live report',()=>window.TPO_APP.returnLive()));form.append(exports);
    form.addEventListener('submit',e=>e.preventDefault());root.append(form,status);if(storageError)root.append(node('p',storageError));return root;
  }
  function rangeKey(key){return ':range:'+key;}
  window.TPO_SETTINGS_UI={panel,effective,apply,reset,download,read,write,range:(id,fallback)=>read(rangeKey(id),fallback),saveRange:(id,v)=>write(rangeKey(id),v)};
})();
