const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),C=require('../js/report-core'),S=C.settings;
const header=['Month','Revenue','COGS','Gross Profit','SG&A','EBIT','Net Income','Quarter'];
function sources(){return [{name:'MonthlyFinancials',raw:[header,['May-26',100,20,80,30,50,40,'Q2 2026'],['Jun-26',200,40,160,60,100,80,'Q2 2026'],['Jul-26',0,0,0,0,0,0,'Q3 2026'],['Aug-27','','','','','','','Q3 2027']]},{name:'Assumptions',raw:[['Customer','Margin'],['Mana',.7],['Beta',.6]]},{name:'CustomerRevenueQuarterly',raw:[['Customer','Quarter','Revenue'],['Mana','Q2 2026',300]]},{name:'CustomerRevenueMonthly',raw:[['Customer','Month','Revenue'],['Mana','Jul-26',0]]}];}
test('settings defaults preserve report tabs and valid zero data in auto mode',()=>{const s=S.normalize({tabs:{customers:{mode:'auto'}}}),a=C.analyze(sources());assert.equal(S.visible(s,a).length,8);s.customers.mana={mode:'auto',label:'Mana',order:0,commentary:true,export:true};assert.ok(S.customerList(s,a).some(c=>c.slug==='mana'));});
test('visibility never excludes revenue or implicitly excludes commentary',()=>{const s=S.normalize({tabs:{financials:{mode:'hide'}},customers:{mana:{mode:'hide'}}}),raw=sources(),a=C.analyze(S.filterSources(raw,s));assert.equal(a.quarterly[0].revenue,300);assert.ok(!S.visible(s,a).some(x=>x.id==='financials'));assert.ok(!S.customerList(s,a).some(x=>x.slug==='mana'));assert.ok(S.commentaryViews(s,a).includes('mana'));assert.ok(S.commentaryViews(s,a).includes('financial-performance'));});
test('AI selection is independent and all report pages can be hidden without invalid settings',()=>{const s=S.normalize({tabs:Object.fromEntries(S.sections.map(x=>[x.id,{mode:'hide',commentary:false}])),customers:{mana:{mode:'hide',commentary:false},beta:{mode:'hide',commentary:false}}}),a=C.analyze(sources());assert.equal(S.visible(s,a).length,0);assert.equal(S.commentaryViews(s,a).length,0);});
test('historical cutoff excludes later months and later full-quarter customer totals',()=>{const s=S.normalize({cutoff:'2026-05'}),filtered=S.filterSources(sources(),s),a=C.analyze(filtered);assert.equal(a.latest.month,'May-26');assert.equal(a.quarterly[0].revenue,100);assert.equal(a.cq.length,0);assert.equal(filtered[0].raw[2][1],'');assert.equal(sources()[0].raw[2][1],200);});
test('quarter-end cutoff preserves matching customer ledger and ignores empty future slots',()=>{const a=C.analyze(S.filterSources(sources(),S.normalize({cutoff:'2026-06'})));assert.equal(a.quarterly[0].revenue,300);assert.equal(a.cq[0].values[0],300);assert.equal(a.latest.month,'Jun-26');});
test('malformed shared configuration fails with actionable validation',()=>{for(const bad of [{version:2},{cutoff:'2999-01'},{decimals:9},{tabs:{overview:{mode:'invisible'}}},{customers:JSON.parse('{"__proto__":{}}')},{tabs:{overview:{export:'false'}}}])assert.throws(()=>S.normalize(bad));assert.throws(()=>S.fromSources([{name:'Report Settings',raw:[['Something else'],['Configuration','{}']]}]),/expected/);});
test('display changes do not alter calculation fingerprint',()=>{const raw=sources(),a=C.analyze(S.filterSources(raw,S.normalize({}))),b=C.analyze(S.filterSources(raw,S.normalize({money:'millions',decimals:2,density:'compact',tabs:{overview:{label:'Board summary'}}})));assert.equal(C.fingerprint(a),C.fingerprint(b));});
test('website shaper applies settings cut-off to company totals',()=>{const window={TPOCore:C};const ctx=vm.createContext({window,AbortController,URL,console,setTimeout,clearTimeout});vm.runInContext(fs.readFileSync('js/data.js','utf8'),ctx);const map=Object.fromEntries(sources().map(s=>[s.name,s.raw]));map['Report Settings']=[['Setting','Value'],['Configuration',JSON.stringify(S.normalize({cutoff:'2026-05'}))]];const shaped=window.TPO_DATA.shape(map);assert.equal(shaped.monthly.at(-1).month,'May-26');assert.equal(shaped.quarterly.quarters[0].revenue,100);assert.equal(shaped.customerEcon.customers.length,0);});
test('browser preferences survive reload and reset follows shared defaults',()=>{const storage=new Map();function boot(fail=false){const window={TPOCore:C,TPO_CONFIG:{SHEET_ID:'fixture'},dispatchEvent(){}};const ctx=vm.createContext({window,Event:class{},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>{if(fail)throw Error('blocked');storage.set(k,v);}},console});vm.runInContext(fs.readFileSync('js/settings.js','utf8'),ctx);return window.TPO_SETTINGS_UI;}let ui=boot();ui.apply({money:'millions'});ui=boot();assert.equal(ui.effective({money:'full'}).money,'millions');ui.reset();assert.equal(ui.effective({money:'full'}).money,'full');assert.doesNotThrow(()=>boot(true).apply({money:'thousands'}));});
test('currency display honors source currency and does not convert values',()=>{const window={TPOCore:C},ctx=vm.createContext({window,Intl});vm.runInContext(fs.readFileSync('js/compute.js','utf8'),ctx);window.TPO_COMPUTE.setFormat(S.normalize({money:'thousands',decimals:2}),'USD');assert.match(window.TPO_COMPUTE.fmtMoneyFull(12345),/12\.35K/);assert.match(window.TPO_COMPUTE.fmtMoneyFull(0),/0\.00K/);assert.equal(window.TPO_COMPUTE.fmtMoney(null),'—');});
